prog: agence.o vehicule.o voiture.o camion.o site.o listeSite.o main.o client.o etat.o 
	g++ -Wall agence.o vehicule.o voiture.o camion.o site.o listeSite.o main.o client.o etat.o -o prog
agence.o: agence.h agence.cpp
	g++ -Wall -c agence.cpp -o agence.o
vehicule.o: vehicule.h vehicule.cpp
	g++ -Wall -c vehicule.cpp -o vehicule.o
voiture.o: voiture.h voiture.cpp
	g++ -Wall -c voiture.cpp -o voiture.o
camion.o: camion.h camion.cpp
	g++ -Wall -c camion.cpp -o camion.o
site.o: site.h site.cpp
	g++ -Wall -c site.cpp -o site.o
listeSite.o: listeSite.h listeSite.cpp
	g++ -Wall -c listeSite.cpp -o listeSite.o
main.o: main.cpp
	g++ -Wall -c main.cpp -o main.o
client.o: client.h client.cpp
	g++ -Wall -c client.cpp -o client.o
etat.o: etat.h etat.cpp
	g++ -Wall -c etat.cpp -o etat.o


